final List<Map<String, dynamic>> ordersJson = [
  {
    'id': '#001',
    'customer': 'Marie Dupont',
    'table': 'Table 5',
    'time': '14:30',
    'date': DateTime.now().subtract(const Duration(hours: 2)),
    'items': [
      {'name': 'Bière Blonde', 'quantity': 2, 'price': 1500},
      {'name': 'Sandwich Club', 'quantity': 1, 'price': 3000},
    ],
    'amount': 6000,
    'status': 'pending',
  },
  {
    'id': '#002',
    'customer': 'Jean Martin',
    'table': 'Table 2',
    'time': '14:25',
    'date': DateTime.now().subtract(const Duration(hours: 3)),
    'items': [
      {'name': 'Café Expresso', 'quantity': 3, 'price': 800},
      {'name': 'Croissant', 'quantity': 1, 'price': 1500},
    ],
    'amount': 3900,
    'status': 'confirmed',
  },
  {
    'id': '#003',
    'customer': 'Anna Moreau',
    'table': 'Table 3',
    'time': '14:35',
    'date': DateTime.now().subtract(const Duration(hours: 1)),
    'items': [
      {'name': 'Vin Rouge', 'quantity': 1, 'price': 4000},
      {'name': 'Planche Mixte', 'quantity': 1, 'price': 5000},
    ],
    'amount': 9000,
    'status': 'pending',
  },
  {
    'id': '#004',
    'customer': 'Pierre Leroy',
    'table': 'Table 1',
    'time': '13:15',
    'date': DateTime.now().subtract(const Duration(hours: 5)),
    'items': [
      {'name': 'Heineken', 'quantity': 4, 'price': 1500},
      {'name': 'Coca-Cola', 'quantity': 2, 'price': 1500},
    ],
    'amount': 9000,
    'status': 'confirmed',
  },
  {
    'id': '#005',
    'customer': 'Sophie Bernard',
    'table': 'Table 7',
    'time': '15:00',
    'date': DateTime.now(),
    'items': [
      {'name': 'Mojito', 'quantity': 2, 'price': 2500},
      {'name': 'Sprite', 'quantity': 1, 'price': 1000},
    ],
    'amount': 6000,
    'status': 'pending',
  },
  {
    'id': '#006',
    'customer': 'Luc Petit',
    'table': 'Table 4',
    'time': '12:45',
    'date': DateTime.now().subtract(const Duration(hours: 6)),
    'items': [
      {'name': 'Bordeaux Rouge', 'quantity': 1, 'price': 2800},
    ],
    'amount': 2800,
    'status': 'refused',
  },
  {
    'id': '#007',
    'customer': 'Emma Rousseau',
    'table': 'Table 6',
    'time': '14:50',
    'date': DateTime.now().subtract(const Duration(minutes: 30)),
    'items': [
      {'name': 'Gin Tonic', 'quantity': 3, 'price': 2800},
      {'name': 'Piña Colada', 'quantity': 1, 'price': 3000},
    ],
    'amount': 11400,
    'status': 'pending',
  },
  {
    'id': '#008',
    'customer': 'Thomas Dubois',
    'table': 'Table 8',
    'time': '13:30',
    'date': DateTime.now().subtract(const Duration(hours: 4)),
    'items': [
      {'name': 'Castel', 'quantity': 6, 'price': 1200},
    ],
    'amount': 7200,
    'status': 'confirmed',
  },
];
