/* =========================================================
   JSON PRODUITS – STRICTEMENT INCHANGÉ
   ========================================================= */

final List<Map<String, dynamic>> productsJson = [
  {
    "id": "p1",
    "name": "Heineken",
    "category": "Bière",
    "boissonType": "Bière blonde",
    "priceCfa": 1500,
    "oldPriceCfa": null,
    "promotion": null,
    "stock": 24,
    "status": "available",
    "image": "assets/images/boisson9.jpg",
  },
  {
    "id": "p2",
    "name": "Castel",
    "category": "Bière",
    "boissonType": "Bière brune",
    "priceCfa": 1200,
    "oldPriceCfa": null,
    "promotion": null,
    "stock": 18,
    "status": "available",
    "image": "assets/images/boisson2.jpg",
  },
  {
    "id": "p3",
    "name": "Strawberry Daiquiri",
    "category": "Cocktail",
    "boissonType": "Cocktail aux fraises",
    "priceCfa": 800,
    "oldPriceCfa": null,
    "promotion": null,
    "stock": 10,
    "status": "available",
    "image": "assets/images/cocktail2.jpg",
  },
  {
    "id": "p4",
    "name": "Mojito",
    "category": "Soft",
    "boissonType": "Cocktail sans alcool",
    "priceCfa": 2500,
    "oldPriceCfa": null,
    "promotion": null,
    "stock": 0,
    "status": "unavailable",
    "image": "assets/images/boisson3.jpg",
  },
  {
    "id": "p5",
    "name": "Piña Colada",
    "category": "Vin",
    "boissonType": "Cocktail à l'ananas",
    "priceCfa": 3000,
    "oldPriceCfa": null,
    "promotion": null,
    "stock": 6,
    "status": "available",
    "image": "assets/images/boisson4.jpg",
  },
  {
    "id": "p6",
    "name": "Chardonnay",
    "category": "Vin",
    "boissonType": "Vin blanc",
    "priceCfa": 4000,
    "oldPriceCfa": null,
    "promotion": null,
    "stock": 9,
    "status": "available",
    "image": "assets/images/boisson5.jpg",
  },
  {
    "id": "p7",
    "name": "Gin Tonic",
    "category": "Spiritueux",
    "boissonType": "Cocktail au gin",
    "priceCfa": 2800,
    "oldPriceCfa": null,
    "promotion": null,
    "stock": 7,
    "status": "available",
    "image": "assets/images/boisson6.jpg",
  },
  {
    "id": "p8",
    "name": "Coca-Cola",
    "category": "Promotion",
    "boissonType": "Soda",
    "priceCfa": 1500,
    "oldPriceCfa": 1800,
    "promotion": "Achetez 3, recevez 1 offert",
    "stock": 30,
    "status": "available",
    "image": "assets/images/boisson7.jpg",
  },
  {
    "id": "p9",
    "name": "Bordeaux Rouge",
    "category": "Promotion",
    "boissonType": "Vin rouge",
    "priceCfa": 2800,
    "oldPriceCfa": 3500,
    "promotion": "Prix réduit",
    "stock": 4,
    "status": "available",
    "image": "assets/images/boisson8.jpg",
  },
  {
    "id": "p10",
    "name": "Sprite",
    "category": "Promotion",
    "boissonType": "Soda",
    "priceCfa": 1000,
    "oldPriceCfa": 1200,
    "promotion": "Achetez 2, recevez 1 offert",
    "stock": 0,
    "status": "unavailable",
    "image": "assets/images/boisson2.jpg",
  },
];
